// console.log(a)
// console.log( 3 + 7)
// 3 + 7 code not work once we get error 
//to avoid this we use try catch block



// try{
//     console.log(a)
// }catch(err){
//     console.log(err)
// }
// console.log(3 + 9)